### ISSUE TITLE
Unloading machine in Mining Asteroid is wrong direction

### ISSUE THREAD

**Issue by Crimsonzed** [athompson11/Paradise#10]
**Problem Description**:
Unloading machine in Mining Asteroid is wrong direction

**What did you expect to happen**: 
The machine should be pointing south so it can unload properly

**What happened instead**:
It is pointed east, so it is unaccesible

**Why is this bad/What are the consequences:**
Miners cant do their job

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by athompson11** [comment]
There was a note on the station requesting you use the ore redemption machine, there's no real point in even having the old processor.

**Comment by athompson11** [comment]
The Mining Station is going to be reworked to remove it.

**Comment by Ltmayday** [comment]
Note: i been assigned to the rework.

Whats been done?: Mining Office been moved from the station to the old processor area on the outpost to make it a bit easier in a way, added floodlights and other goodies in the office as well

**Comment by Crimsonzed** [comment]
A problem is that nobody knows how to use the ore redemption machine.

**Comment by Ltmayday** [comment]
good thing i do....but as i found out there was no input or output for said machine...soooo i place them in...input is north of the machine and the output is south of it...place ore box or ore on the ground north of it and wait...check machine for points and the ore...to take ore out..place ID in and hit what ore you want...it will spit it out on the tile you near or south of the Machine...don't forget your ID
