### ISSUE TITLE
Brig Physicians don't have Security access

### ISSUE THREAD

**Issue by Sheep-wolf** [athompson11/Paradise#12]
**Problem Description**:
Brig Physicians are lacking access to security. Can't check what they're missing specifically.

**What did you expect to happen**: 
I expected to get into Security, the brig specifically.

**What happened instead**:
The doors blinked red, all of them.

**Why is this bad/What are the consequences:**
I can't do my job at all.

**Steps to reproduce the problem**:
Walk into a door as a Brig Physician.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Nothing.

**Comment by athompson11** [comment]
Can not replicate with latest update of code base. Marking as invalid and closing.
