### ISSUE TITLE
Cargo shuttle's conveyor is borked

### ISSUE THREAD

**Issue by CrystalNole** [athompson11/Paradise#7]
**Problem Description**:
What is the problem?
Cargo shuttle's upper conveyor has a belt facing the wrong way
**What did you expect to happen**: For them all to be facing the right way.
Why do you think this is a bug? Because the conveyor just pushes you back and forth

**What happened instead**:
How is what happened different from what you expected? 

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by Ltmayday** [comment]
Hello, i been assigned to this, 

Please provide a photo of said belt and i will jump on to it and fix it...

Mapper Team
