### ISSUE TITLE
AI can't call emergancy shuttle

### ISSUE THREAD

**Issue by bewawolf19** [athompson11/Paradise#9]
**Problem Description**:
If you click the "Call Emergancy shuttle button", a reason window pops up. No matter what you type, it will close after you hit "ok" with the message "You must provide a reason"

**What did you expect to happen**: 
For the emergancy shuttle to be called

**What happened instead**:
AI died (Me), crew died, ~18 bald assistants who were handcuffed in security died

**Why is this bad/What are the consequences:**
'cuz, we got the call button and can't use it. Either remove it or make it work.

**Steps to reproduce the problem**:
Be an AI. Have slovak on. When station starts going dead, try calling emergancy shuttle. When it doesn't come, die.

**Comment by Slovakiani** [comment]
I love being part of the problem!

**Comment by athompson11** [comment]
Cannot be replicated during testing with latest update.
